nodeLinker: node-modules

packageExtensions:
  '@parcel/bundler-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/compressor-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/namer-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/node-resolver-core@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-css@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-htmlnano@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-svgo@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/optimizer-swc@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-css@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-html@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-js@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/packager-svg@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/plugin@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/reporter-cli@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/reporter-dev-server@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/reporter-tracer@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/resolver-default@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-browser-hmr@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-js@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-react-refresh@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/runtime-service-worker@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-babel@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-css@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-html@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-json@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-postcss@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-posthtml@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-raw@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-react-refresh-wrap@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/transformer-svg@*':
    peerDependencies:
      '@parcel/core': '*'
  '@parcel/types@*':
    peerDependencies:
      '@parcel/core': '*'
  'parcel-reporter-clean-dist@*':
    peerDependencies:
      '@parcel/core': '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
